name: Smoke Testing
on: [deployment_status]
jobs:
  pr-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      # display the vercel preview link
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
      - name: Stores The "vercel_preview_link" value 🔒
        run: |
          echo "vercel_preview_link=${{github.event.deployment_status.target_url}}" >> $GITHUB_ENV

      - name: Prints The "vercel_preview_link" value 🖨
        run: |
          echo "${{env.vercel_preview_link}}"

      # run tests tagged "smoke"
      # https://github.com/bahmutov/cypress-grep
      - name: Runs Smoke Tests 💨
        # https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v4
        with:
          start: npx cypress run
          # quote the url to be safe against YML parsing surprises
          # run only the tests tagged smoke
          env: grepTags=smoke
        # environment variables while running Cypress
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
